name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.itsatrap.ItsATrap
api-version: 1.18

permissions:
  itsatrap.admin:
    description: Permission to administer the plugin.
    default: op

commands:
  itsatrap:
    description: ${project.name} administrative command.
    permission: itsatrap.admin
    usage: |

      §e/<command> help §f- Show usage help.
      §e/<command> reload §f- Reload the configuration.
      §e/<command> types §f- List all possible trap replacement types.
      §e/<command> type §f[§e<type>§f] - Force all traps to be of the
        specified type until the next restart (for testing purposes).
        If the type is omitted, normal random type selection resumes.
